### ISSUE TITLE
Bug Baterias Invertidas  

### ISSUE THREAD

**Issue by insanitus** [greenoneo0/BENOTL#4]
Hola;

 ¿Ya corrigieron el **bug** de poner las _baterias invertidas_ para que funcione la badge?

 Saludos

**Comment by insanitus** [comment]
Hola, ¿Como van? :)

**Comment by sabas1080** [comment]
@wero1414 @greenoneo0 hubo una correcion?

**Comment by eacandelas** [comment]
Ninguna corrección.
El estatus actual es que ya tenemos los stenciles que faltaban.
Estamos esperando un huevo para poderlos meter a re manufactura (quitar los componentes dañados y resoldar) principalmente los usb/serial. Y soldar las tarjetas que vienen vírgenes.

**Comment by insanitus** [comment]
¿Entonces @greenoneo0  crees que llevan un 48% de avance?

**Comment by insanitus** [comment]
> Ninguna corrección.
> El estatus actual es que ya tenemos los stenciles que faltaban.
> Estamos esperando un huevo para poderlos meter a re manufactura (quitar los componentes dañados y resoldar) principalmente los usb/serial. Y soldar las tarjetas que vienen vírgenes.

Hola @eacandelas ¿Como va el proyecto?, ¿En que andan atorados? @sabas1080

**Comment by sabas1080** [comment]
Corregido error de baterías en las versiones que se mandaron a produccion Chica y Tesla
