### ISSUE TITLE
Listado de Componentes BOM

### ISSUE THREAD

**Issue by insanitus** [greenoneo0/BENOTL#5]
Hola;

 ¿Van a subir el Listado de Componentes / Bill Of Materials?

**Comment by sabas1080** [comment]
Hola @insanitus 

En el esquematico de Kicad podrias encontrarlo facilmente en las propiedades de cada componente

Aun asi acabo de generar el BOM en CSV y subirlo

https://github.com/greenoneo0/BENOTL/blob/master/BENOTL-HW/Chica/talentBadge.csv

Saludos

**Comment by insanitus** [comment]
> Hola @insanitus
> 
> En el esquematico de Kicad podrias encontrarlo facilmente en las propiedades de cada componente
> 
> Aun asi acabo de generar el BOM en CSV y subirlo
> 
> https://github.com/greenoneo0/BENOTL/blob/master/BENOTL-HW/Chica/talentBadge.csv
> 
> Saludos


¡ Muchas Gracias !
