### ISSUE TITLE
¿Y el firmware?

### ISSUE THREAD

**Issue by insanitus** [greenoneo0/BENOTL#6]
Hola buen día;

Revisando parte del git de las badge, noto que, _el apartado del firmware esta totalmente vacio_

`https://github.com/eacandelas/BENOTL/tree/master/BENOTL-FW`

De antemano, les agredeceria, si lo pudieran subir (n_n)

Saludos

@wero1414 @sabas1080 @eacandelas @ElectronicCats

**Comment by sabas1080** [comment]
Añadido ejemplo para neopixeles
