### ISSUE TITLE
Actualizar el Firmware para que funcione el esp

### ISSUE THREAD

**Issue by insanitus** [greenoneo0/BENOTL#7]
Hola, buen día;

 De momento el Firmware tiene un funcionamiento limitado, ya que única y exclusivamente solo han;
```

Añadido ejemplo para neopixeles

_Originally posted by @sabas1080 in https://github.com/eacandelas/BENOTL/issues/6#issuecomment-828137069_
```

Más la parte del esp queda fuera de funcionamiento, por falta de código, y acorde a los objetivos que se habían puesto previamente;

```
Funciones:
- Intercambio de credenciales IR y Web
- Funcionalidad de TVGBone
- Mesh

También se puede usar para:
- WiFi Spoofing
- WiFi deauthentication 
```

Son las funciones que hacen falta en el código del firmware.

¿Y este es el datahseet correspondiente al esp que utiliza la badge?
https://www.espressif.com/sites/default/files/documentation/0c-esp-wroom-02_datasheet_en.pdf

 De antemano agradezco el tiempo que se toman, en leer y atender este issue.

@wero1414 @sabas1080 @eacandelas @ElectronicCats

Saludos

**Comment by sabas1080** [comment]
Hay varios proyectos en los que te puedes basar y crear lo que mencionas 

https://github.com/lspoplove/Deauther-Project
https://github.com/SpacehuhnTech/esp8266_deauther
https://github.com/SpacehuhnTech/WiFiDuck
https://github.com/spacehuhn/esp8266_beaconSpam
https://github.com/spacehuhn/PacketMonitor
https://github.com/spacehuhn/ArduinoPcap
https://github.com/spacehuhn/wifi_ducky
https://github.com/spacehuhn/wifi_keylogger
https://github.com/SpacehuhnTech/Huhnitor 

Las partes involucradas no podemos dar más soporte a este proyecto por tiempo y los recursos que se destinaron para crearlo, pero el proyecto tiene todo lo necesario para adaptarlo y hacerlo funcionar
